### ISSUE TITLE
error indexupdate because of faulty document structure

### ISSUE THREAD

**Issue by guenterh** [swissbib/content2SearchDocs#39]
Indexing again SOLR7 after "Gesamtexport" causes an exception for one document:

```text
nohup: ignoring input
prechecks finished ...
given inputdir: /swissbib_index/solrDocumentProcessing/MarcToSolrTest/data/outputfiles
start indexing ...

org.apache.solr.client.solrj.impl.CloudSolrClient$RouteException: Error from server at http://131.152.230.37:8080/solr/green_shard1_replica_n1: Exception writing document id 358773261 to the index; possible analysis error: startOffset must be non-negative, and endOffset must be >= startOffset, and offsets must not go backwards startOffset=339,endOffset=346,lastStartOffset=340 for field 'title_alt'
        at org.apache.solr.client.solrj.impl.CloudSolrClient.directUpdate(CloudSolrClient.java:551)
        at org.apache.solr.client.solrj.impl.CloudSolrClient.sendRequest(CloudSolrClient.java:1014)
        at org.apache.solr.client.solrj.impl.CloudSolrClient.requestWithRetryOnStaleState(CloudSolrClient.java:885)
        at org.apache.solr.client.solrj.impl.CloudSolrClient.requestWithRetryOnStaleState(CloudSolrClient.java:947)
        at org.apache.solr.client.solrj.impl.CloudSolrClient.requestWithRetryOnStaleState(CloudSolrClient.java:947)
        at org.apache.solr.client.solrj.impl.CloudSolrClient.requestWithRetryOnStaleState(CloudSolrClient.java:947)
        at org.apache.solr.client.solrj.impl.CloudSolrClient.requestWithRetryOnStaleState(CloudSolrClient.java:947)
        at org.apache.solr.client.solrj.impl.CloudSolrClient.requestWithRetryOnStaleState(CloudSolrClient.java:947)
        at org.apache.solr.client.solrj.impl.CloudSolrClient.request(CloudSolrClient.java:818)
        at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:194)
        at org.apache.solr.client.solrj.SolrClient.add(SolrClient.java:106)
        at org.apache.solr.client.solrj.SolrClient.add(SolrClient.java:71)
        at org.swissbib.solr.SolrClientWrapper.add(SolrClientWrapper.java:85)
        at org.swissbib.solr.IndexerMFClient.lambda$process$1(IndexerMFClient.java:160)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at org.swissbib.solr.IndexerMFClient.process(IndexerMFClient.java:159)
        at org.swissbib.solr.ExtendedFileOpener.process(ExtendedFileOpener.java:81)
        at org.swissbib.solr.ExtendedFileOpener.process(ExtendedFileOpener.java:24)
        at org.metafacture.files.DirReader.dir(DirReader.java:79)
        at org.metafacture.files.DirReader.dir(DirReader.java:76)
        at org.metafacture.files.DirReader.process(DirReader.java:57)
        at org.metafacture.files.DirReader.process(DirReader.java:35)
        at org.metafacture.flux.parser.StringSender.process(StringSender.java:38)
        at org.metafacture.flux.parser.Flow.start(Flow.java:110)
        at org.metafacture.flux.parser.FluxProgramm.start(FluxProgramm.java:156)
        at org.metafacture.runner.Flux.main(Flux.java:79)
Caused by: org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://131.152.230.37:8080/solr/green_shard1_replica_n1: Exception writing document id 358773261 to the index; possible analysis error: startOffset must be non-negative, and endOffset must be >= startOffset, and offsets must not go backwards startOffset=339,endOffset=346,lastStartOffset=340 for field 'title_alt'
        at org.apache.solr.client.solrj.impl.HttpSolrClient.executeMethod(HttpSolrClient.java:643)
        at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:255)
        at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:244)
        at org.apache.solr.client.solrj.impl.LBHttpSolrClient.doRequest(LBHttpSolrClient.java:483)
        at org.apache.solr.client.solrj.impl.LBHttpSolrClient.request(LBHttpSolrClient.java:413)
        at org.apache.solr.client.solrj.impl.CloudSolrClient.lambda$directUpdate$0(CloudSolrClient.java:528)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.apache.solr.common.util.ExecutorUtil$MDCAwareThreadPoolExecutor.lambda$execute$0(ExecutorUtil.java:188)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
~


```

**Comment by liowalter** [comment]
@guenterh : is this still open ?

**Comment by liowalter** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[content2SearchDocs] error indexupdate because of faulty document structure](https://trello.com/c/gJPl6BRZ/306-content2searchdocs-error-indexupdate-because-of-faulty-document-structure)
